// This webpack is only for building Sass (.scss) to CSS
const path = require('path');
// This plugin will extract CSS into separate files
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
// This plugin removes empty scripts generated by usage 
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// input file: src/src/scss/style.scss
// output file: wwwroot/styles/style.scss

module.exports = {
  entry: {
    style: './src/styles/style',
  },
  mode: 'development',
  output: {
    path: path.resolve(__dirname, 'wwwroot/styles'), // output dir must be absolute path
    // filename: '[name].js',
  },
  resolve: {
    extensions: ['.scss'],
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          // Extract to CSS file
          MiniCssExtractPlugin.loader,
          // Translates CSS to CommonJS and ignore solving URL of images
          'css-loader?url=false',
          // Compiles Sass to CSS
          'sass-loader',
        ],
        exclude: /node_modules/,
      },
    ]// End rules
  },
  plugins: [
    new RemoveEmptyScriptsPlugin({ verbose: true }),
    new MiniCssExtractPlugin({
      // Configure the output of CSS.
      // It is relative to output dir, only relative path work, absolute path does not work.
      filename: "[name].css",
    }),
  ],
};